{"name": "test_2", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 4 == 5", "trace": "@pytest.mark.xfail\n    def test_2():\n        print(\"Test 3\")\n>       assert 4==5\nE       assert 4 == 5\n\ntest_firstcode.py:20: AssertionError"}, "attachments": [{"name": "stdout", "source": "16ea4d46-8cb8-4e4c-b87d-1a3638ff20a4-attachment.txt", "type": "text/plain"}], "start": 1743727498843, "stop": 1743727498843, "uuid": "1b76eac6-6c17-46a9-a2d8-040f7f58db72", "historyId": "3dd8fae618b3b09de58ad911f3a13a58", "testCaseId": "3dd8fae618b3b09de58ad911f3a13a58", "fullName": "test_firstcode#test_2", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_firstcode"}, {"name": "host", "value": "PG02YMX2"}, {"name": "thread", "value": "26772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_firstcode"}]}